minimumReleaseAge: 0

packages:
  - ts-core
  - ts-markets
  - ts-cloud
  - rust
  - probes


allowBuilds:
  esbuild: true
  msw: true
  nx: true
  protobufjs: true
  sharp: true
  workerd: true

onlyBuiltDependencies:
  - esbuild
  - msw
  - nx
  - protobufjs
  - sharp
  - workerd
