name = "ts-cloud"
main = "src/platform/cloudflare/worker.ts"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat"]

[vars]
PLATFORM = "cloudflare"
# CORELIB_TURSO_URL = ""
# CORELIB_TURSO_TOKEN = ""
