// =============================================
// FILE: ts-core/scripts/postinstall.js
// PURPOSE: Post-install script for downloading Rust binaries from GitHub Releases.
// Maps current OS/Arch to the correct prebuilt binary.
// Skips download if MODE=development (local dev).
// =============================================

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

async function run() {
	const MODE = process.env.MODE || "production";
	const isDev = MODE === "development";
	const isCI = !!process.env.GITHUB_ACTIONS;

	console.log(`[POSTINSTALL] Running in ${MODE} mode (CI: ${isCI})`);

	if (isDev || isCI) {
		console.log("[POSTINSTALL] Local development or CI mode detected. Skipping binary download.");
		process.exit(0);
	}

	const platform = process.platform;
	const arch = process.arch;
	let artifactName = "";

	// Map the Node environment to the artifacts generated by our GitHub Action
	if (platform === "win32" && arch === "x64") artifactName = "corelib-rust-win32-x64.node";
	else if (platform === "linux" && arch === "x64") artifactName = "corelib-rust-linux-x64.node";
	else if (platform === "darwin" && arch === "x64") artifactName = "corelib-rust-darwin-x64.node";
	else if (platform === "darwin" && arch === "arm64") artifactName = "corelib-rust-darwin-arm64.node";
	else {
		console.warn(`[POSTINSTALL] Unsupported platform/arch: ${platform}/${arch}. You may need to build the native binary manually.`);
		process.exit(0);
	}

	try {
		// 1. Get the package version dynamically so it matches the GitHub Release tag
		const pkgPath = new URL("../package.json", import.meta.url);
		const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
		const version = pkg.version;

		// 2. Identify the Github Repo (Use GITHUB_REPOSITORY if in CI, or fallback to your hardcoded path)
		const repo = process.env.GITHUB_REPOSITORY || "ckir/corelib";
		const url = `https://github.com/${repo}/releases/download/v${version}/${artifactName}`;

		console.log(`[POSTINSTALL] Downloading binary from ${url}...`);

		// 3. Fetch the binary using Node's native fetch
		const response = await fetch(url);
		if (!response.ok) {
			throw new Error(`HTTP error! status: ${response.status} ${response.statusText}`);
		}

		// 4. Save the binary directly to the expected location
		const arrayBuffer = await response.arrayBuffer();
		const buffer = Buffer.from(arrayBuffer);
		const dest = resolve(import.meta.dirname, "../corelib-rust.node");
		
		writeFileSync(dest, buffer);

		console.log(`[POSTINSTALL] Successfully downloaded ${artifactName} to ${dest}`);
	} catch (error) {
		console.error(`[POSTINSTALL] Failed to download binary:`, error);
		console.warn("[POSTINSTALL] You may need to build the Rust binary manually using `pnpm run build` in the rust directory.");
		
		// Exiting with 0 so it doesn't fail the entire module installation just because of a network block.
		// The user can still run the Rust build manually if the download fails.
		process.exit(0);
	}
}

run();
