/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Returns the Cargo package version as a string.
 * Used by the TS FFI bridge (`getVersion`).
 */
export declare function getVersion(): string

/**
 * Logs a message in Rust and returns the input value doubled.
 * Used by the TS FFI bridge (`logAndDouble`).
 */
export declare function logAndDouble(msg: string, value: number): number
