/* auto-generated by NAPI-RS */
/* eslint-disable */
/** N-API wrapper for the Alpaca price streamer, enabling its use in JavaScript environments. */
export declare class AlpacaStreaming {
  /** Constructs a new `AlpacaStreaming` instance with the provided JavaScript callback functions. */
  constructor(onLog: ((err: Error | null, arg: LogRecord) => any), onPricing: ((err: Error | null, arg: AlpacaPricingData) => any), onEvent: ((err: Error | null, arg: EventRecord) => any))
  /** Initializes the streamer with configuration parameters. */
  init(config: AlpacaConfig): Promise<void>
  /** Starts the long-running streaming task. */
  start(): Promise<void>
  /** Adds a list of symbols to the active stream. */
  subscribe(symbols: Array<string>): Promise<void>
  /** Removes a list of symbols from the active stream. */
  unsubscribe(symbols: Array<string>): Promise<void>
  /** Clears all subscriptions and stops the stream. */
  clean(): Promise<void>
  /** Gracefully stops the streaming task. */
  stop(): Promise<void>
}

/** N-API wrapper for the price streamer, enabling its use in JavaScript environments. */
export declare class YahooStreaming {
  /** Constructs a new `YahooStreaming` instance with the provided JavaScript callback functions. */
  constructor(onLog: ((err: Error | null, arg: LogRecord) => any), onPricing: ((err: Error | null, arg: JsPricingData) => any), onEvent: ((err: Error | null, arg: EventRecord) => any))
  /** Initializes the streamer with configuration parameters. */
  init(config: YahooConfig): Promise<void>
  /** Starts the long-running streaming task. */
  start(): Promise<void>
  /** Adds a list of symbols to the active stream. */
  subscribe(symbols: Array<string>): Promise<void>
  /** Removes a list of symbols from the active stream. */
  unsubscribe(symbols: Array<string>): Promise<void>
  /** Clears all subscriptions and stops the stream. */
  clean(): Promise<void>
  /** Gracefully stops the streaming task. */
  stop(): Promise<void>
}

/** Configuration parameters for the Alpaca price streamer. */
export interface AlpacaConfig {
  /** Optional path to the `redb` database file. Defaults to a temporary directory. */
  dbPath?: string
  /** Threshold in seconds for silence detection before triggering a reconnect. */
  silenceSeconds?: number
  /** Optional override for the WebSocket URL (defaults to IEX stream or `APCA_API_BASE_URL`). */
  baseUrl?: string
  /** Alpaca API Key ID. Falls back to `APCA_API_KEY_ID` environment variable. */
  keyId?: string
  /** Alpaca API Secret Key. Falls back to `APCA_API_SECRET_KEY` environment variable. */
  secretKey?: string
}

/** A unified representation of Alpaca pricing data, consolidating Trades, Quotes, and Bars. */
export interface AlpacaPricingData {
  /** The ticker symbol of the instrument (e.g., "AAPL"). */
  symbol: string
  /** The type of data received ("quote", "trade", "bar"). */
  messageType: string
  /** The primary price (last trade price, close price for bars, or bid price for quotes). */
  price: number
  /** The current bid price (applicable for quotes). */
  bidPrice: number
  /** The current ask price (applicable for quotes). */
  askPrice: number
  /** The volume associated with the event. */
  volume: number
  /** The timestamp provided by the Alpaca exchange. */
  timestamp: string
}

/** Represents a lifecycle event emitted by the streamer. */
export interface EventRecord {
  /** The type of event (e.g., "connected", "disconnected", "reconnecting", "error"). */
  type: string
  /** Optional metadata or error message associated with the event. */
  data?: string
}

/**
 * Returns the Cargo package version as a string.
 * Used by the TS FFI bridge (`getVersion`).
 *
 * # Returns
 * The version string from `Cargo.toml`.
 */
export declare function getVersion(): string

/**
 * An N-API compatible object representing pricing data.
 *
 * This struct mirrors `PricingData` but uses `f64` for all floating-point numbers
 * to ensure precision when passed to JavaScript.
 */
export interface JsPricingData {
  id: string
  price: number
  time: number
  currency: string
  exchange: string
  quoteType: number
  marketHours: number
  changePercent: number
  dayVolume: number
  dayHigh: number
  dayLow: number
  change: number
  shortName: string
  expireDate: number
  openPrice: number
  previousClose: number
  strikePrice: number
  underlyingSymbol: string
  openInterest: number
  optionType: number
}

/**
 * Logs a message in Rust and returns the input value doubled.
 * Used by the TS FFI bridge (`logAndDouble`).
 *
 * # Arguments
 * * `msg` - The message to log to stdout.
 * * `value` - The integer value to double.
 *
 * # Returns
 * The input `value` multiplied by 2.
 */
export declare function logAndDouble(msg: string, value: number): number

/** Represents a single log entry formatted for the Corelib StrictLogger. */
export interface LogRecord {
  /** The log level (e.g., "info", "error", "trace"). */
  level: string
  /** The primary log message. */
  msg: string
  /** Optional structured data serialized as a JSON string. */
  extras?: string
}

/** Represents the specific trading session of the quote. */
export declare const enum MarketHoursType {
  /** Before the official market open. */
  PreMarket = 0,
  /** During official trading hours. */
  RegularMarket = 1,
  /** After the official market close. */
  PostMarket = 2,
  /** General catch-all for non-regular hours. */
  ExtendedHoursMarket = 3
}

/** Distinguishes between Call and Put options. */
export declare const enum OptionType {
  /** A call option. */
  Call = 0,
  /** A put option. */
  Put = 1
}

/** Categorizes the type of financial instrument providing the data. */
export declare const enum QuoteType {
  None = 0,
  Altsymbol = 5,
  Heartbeat = 7,
  Equity = 8,
  Index = 9,
  Mutualfund = 11,
  Moneymarket = 12,
  Option = 13,
  Currency = 14,
  Warrant = 15,
  Bond = 17,
  Future = 18,
  Etf = 20,
  Commodity = 23,
  Ecnquote = 28,
  Cryptocurrency = 41,
  Indicator = 42,
  Industry = 1000
}

/** Configuration parameters for the Yahoo price streamer. */
export interface YahooConfig {
  /** Optional path to the `redb` database file. Defaults to a temporary directory. */
  dbPath?: string
  /** Threshold in seconds for silence detection before triggering a reconnect. */
  silenceSeconds?: number
}
