/* auto-generated by NAPI-RS */
/* eslint-disable */
/** N-API wrapper for JS usage. */
export declare class YahooStreaming {
  constructor(onLog: ((err: Error | null, arg: LogRecord) => any), onPricing: ((err: Error | null, arg: JsPricingData) => any), onEvent: ((err: Error | null, arg: EventRecord) => any))
  init(config: YahooConfig): Promise<void>
  start(): Promise<void>
  subscribe(symbols: Array<string>): Promise<void>
  unsubscribe(symbols: Array<string>): Promise<void>
  clean(): Promise<void>
  stop(): Promise<void>
}

export interface EventRecord {
  type: string
  data?: string
}

/**
 * Returns the Cargo package version as a string.
 * Used by the TS FFI bridge (`getVersion`).
 */
export declare function getVersion(): string

export interface JsPricingData {
  id: string
  price: number
  time: number
  currency: string
  exchange: string
  quoteType: number
  marketHours: number
  changePercent: number
  dayVolume: number
  dayHigh: number
  dayLow: number
  change: number
  shortName: string
  expireDate: number
  openPrice: number
  previousClose: number
  strikePrice: number
  underlyingSymbol: string
  openInterest: number
  optionType: number
}

/**
 * Logs a message in Rust and returns the input value doubled.
 * Used by the TS FFI bridge (`logAndDouble`).
 */
export declare function logAndDouble(msg: string, value: number): number

export interface LogRecord {
  level: string
  msg: string
  extras?: string
}

/** Represents the specific trading session of the quote. */
export declare const enum MarketHoursType {
  PreMarket = 0,
  RegularMarket = 1,
  PostMarket = 2,
  ExtendedHoursMarket = 3
}

/** Distinguishes between Call and Put options. */
export declare const enum OptionType {
  Call = 0,
  Put = 1
}

/** Categorizes the type of financial instrument providing the data. */
export declare const enum QuoteType {
  None = 0,
  Altsymbol = 5,
  Heartbeat = 7,
  Equity = 8,
  Index = 9,
  Mutualfund = 11,
  Moneymarket = 12,
  Option = 13,
  Currency = 14,
  Warrant = 15,
  Bond = 17,
  Future = 18,
  Etf = 20,
  Commodity = 23,
  Ecnquote = 28,
  Cryptocurrency = 41,
  Indicator = 42,
  Industry = 1000
}

export interface YahooConfig {
  dbPath?: string
  silenceSeconds?: number
}
